import type { Metadata } from "next";

import "./globals.css";
import Header1 from "@/app/smart-housing-components/Header1";
import Footer from "@/app/smart-housing-components/footer/Index";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={""}>
        <Header1 />
        {children}
        <Footer />
      </body>
    </html>
  );
}
