export const CheckOutArry = [
  {
    image: "Housing/d.svg",
    price: "5,970",
    categories: "Popular",
    icon: "Housing/fire.svg",
    view: "Tranquil Haven in the Woods",
    bed: 5,
    bg: "bg-[#FFE1E1] ",
    bath: 8,
    address: "103 Wright CourtBurien, WA 98168",
  },
  {
    image: "Housing/d.svg",
    price: "19,70",
    categories: "New Listing",
    icon: "Housing/h.svg",
    view: "Serene Retreat by the Lake",
    bed: 3,
    bg: "text-[#119BFF]  bg-[#D7EEFF]  ",
    bath: 2,
    address: "1964 Jehovah Drive, VA 22408",
  },
  {
    image: "Housing/d.svg",
    price: "34,50",
    categories: "Discounted Price",
    icon: "Housing/dollor.svg",
    view: "Charming Cottage in the Meadow",
    bed: 4,
    bg: "text-[#00CE3A]  bg-[#F1FFF1] p-[2px]  ",
    bath: 4,
    address: "1508 Centennial Farm RoadHarlan, 51537",
  },
  {
    image: "Housing/d.svg",
    price: "2,389",
    categories: "Popular",
    icon: "Housing/fire.svg",
    view: "Grand Estate on the Hilltop",
    bed: 4,
    bg: "bg-[#FFE1E1] ",
    bath: 4,
    address: "103 Wright CourtBurien, WA 98168",
  },
 
];
